//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class BehaviorDesigner_Runtime_Tasks_CompositeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(BehaviorDesigner.Runtime.Tasks.Composite), typeof(BehaviorDesigner.Runtime.Tasks.ParentTask));
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("AbortType", get_AbortType, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AbortType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			BehaviorDesigner.Runtime.Tasks.Composite obj = (BehaviorDesigner.Runtime.Tasks.Composite)o;
			BehaviorDesigner.Runtime.Tasks.AbortType ret = obj.AbortType;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index AbortType on a nil value");
		}
	}
}

